### ISSUE TITLE
Named components

### ISSUE THREAD

**Issue by jmeas** [jmeas/react-composer#23]
There could be an alternative syntax that supports named components. In this mode, order is not guaranteed, but you get an object back rather than an array.

It's much nicer to do `results.someComponent` rather than `results[0]`.

API:

```jsx
<Composer components={{
    one: <RenderPropComponent {...configOne} />,
    two: <RenderPropComponent {...configTwo} />,
    three: <RenderPropComponent {...configThree} />
  }}>
  {(results) => (
    <MyComponent results={results} />
  )}
</Composer>
```

---

What do folks think?

**Leave a :+1: or :-1: on this comment to let me know!**

**Comment by gnapse** [comment]
I'll work on this.

**Comment by erikthedeveloper** [comment]
I will add that I don't love the idea of adding this. I'm unsure of what benefit it provides beyond supporting multiple/differing preferences, especially considering widespread use and support for array destructuring. I'm sure there are some use cases where this might be handy or some who may prefer this, but I feel like the array in, array out signature is sufficient and familiar (think of `Promise.all`). I worry that this is only adding more API surface area for subjectively little benefit.

**Comment by jmeas** [comment]
@erikthedeveloper I have the same concerns with introducing this API as well.

**Comment by jmeas** [comment]
I'm going to close this as wontfix for now. I agree with @erikthedeveloper 's arguments above that the value add isn't super high. If you disagree, go ahead and add your :+1: to the opening comment! I'm always open to being persuaded :v:
