### ISSUE TITLE
Update `components` prop name to be more accurate?

### ISSUE THREAD

**Issue by jmeas** [jmeas/react-composer#34]
The `components` prop is a little misleading, as @erikthedeveloper points out. You might think you can place components in there, but you can't. It only accepts elements (or functions that return elements).

Because of this, one could argue that a more accurate name for this prop would be `elements`.

The downside to this wording is that I think many people gloss over the difference between components and elements (that's exactly what I did, which is why the prop is named `components` in the first place). This runs the risk of making things more confusing in exchange for the accuracy.

What do folks think? `components=[<A/>]` or `elements=[<A/>]`? 

**Leave a :+1: or a :-1: to this issue to share your opinion!**

And feel free to comment, too, of course :)

**Comment by gnapse** [comment]
My 2 cents: even though you're putting elements in that array, I think the intention is to specify the components that you want to compose. Also, these elements are not the actual ones that are going to be rendered. They are there as a means to pass down the component along any extra optional props each component might need. But the element that ends up rendered is another one generated during the rendering of `Composer`.

**Comment by erikthedeveloper** [comment]
> They are there as a means to pass down the component along any extra optional props each component might need.

@gnapse My concern is that at no point are we passing down "components", but we are actually working with "elements" throughout. Both having very specific/defined meaning in React.

---

From https://github.com/jmeas/react-composer/issues/19

Whether your components are "function components" or "class components", by the time they make it into the `props.components` array they are no longer components, but rather _evaluated components_ which are then _elements_. So by adding this `typeof props.components[n] === 'function'` check we would essentially be asking "Is this already an element or is this a function [element factory]?".

From https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html#components-can-be-classes-or-functions

> **Components Can Be Classes or Functions**
In the code above, Form, Message, and Button are React components. They can either be written as functions or as classes descending from React.Component. [...] However, whether functions or classes, fundamentally **they are all components** to React. They take the props as their input, and **return** the **elements** as their output.

This is related to what I was getting at with:

> I feel like naming in general might warrant discussion where these are being called "components" throughout where they are really "elements" both having a rather specific meaning in React

**Comment by gnapse** [comment]
But from the perspective of the user of this library, they want to compose components. That's why I think how I stated above. Not a huge deal, but if you ask me, I prefer `components={}`.

From my perspective I am stating there **the components** I want to compose, not the actual elements that will be composed. The very sub-title of this library README says "Compose render prop components." It does not say "Compose render prop elements".

**Comment by jmeas** [comment]
These are compelling arguments. I think you’re both right.

From a “developer experience” perspective, I think using the name “components” is preferable, so I’m leaning toward keeping it as-is for now.

Of course, I can be persuaded if a bunch of people think the current name is causing problems 🙂

**Comment by erikthedeveloper** [comment]
@gnapse I do see your point now 😃  I think you've hit the nail on the head with

> [...] components I want to compose, not the actual elements that will be composed [...] README says "Compose render prop components." It does not say "Compose render prop elements".

For me, it is still a little weird to require an array of `elements` or element producing functions but to call them "components", but I can definitely see your point for the public facing API/naming.

https://github.com/jmeas/react-composer/blob/00529c046711fd014ec36ba1000c026f08af8cbc/src/index.js#L54-L61

🤔  Naming can always be such a subjective/gray area. Perhaps we leave it as-is and we can always revisit **if** it really resurfaces/causes confusion.

**Comment by gnapse** [comment]
Yeah, naming stuff can be tricky, you probably know the old saying:

> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

I understand the apparent confusion, but I prefer to privilege what the outer interface of the utility looks like and intends to solve, rather than something that is a bit more internal. Granted this is not 100% internal, because the knowledgeable React user will know that those are elements what are being passed in there, and not components, but we can even be forthcoming in the README about it, if needed, perhaps with a link to this issue as reference.

**Comment by jmeas** [comment]
> Perhaps we leave it as-is and we can always revisit if it really resurfaces/causes confusion.

I think this is a good resolution given what we know right now. I'm going to close out this issue for now, but **feel free to leave a comment if you have more to do to the conversation!**

@erikthedeveloper , thanks again for starting this discussion! It's certainly been interesting to think about... 🤔
